Feature: Bootstrapping
  Scenario: User wants help to get started
    Given a file named "ssh_config" with:
    """
    Host home
      StrictHostKeyChecking ask

    Host *.amazonaws.com
      StrictHostKeyChecking no
    """
    When I run `poet --bootstrap ssh_config --dir ./config.d -o ssh_config`
    Then the exit status should be 0
    And a directory named "config.d" should exist
    And a file named "config.d/ssh_config" should exist
    And the file "config.d/ssh_config" should contain "Host home"
    And the file "ssh_config" should contain "# Generated by poet"